<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-KC8P2PH" failures="1" tests="10" name="com.TestCases.LoginPageTestcases" time="30.623" errors="0" timestamp="2022-09-19T15:24:06 IST" skipped="0">
  <testcase classname="com.TestCases.LoginPageTestcases" name="HeadChk" time="2.627">
    <failure message="The following asserts failed:
	expected [Adminarea demo] but found [Admin area demo]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Adminarea demo] but found [Admin area demo]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.TestCases.LoginPageTestcases.HeadChk(LoginPageTestcases.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- HeadChk -->
  <system-out/>
  <testcase classname="com.TestCases.LoginPageTestcases" name="Wlcchk" time="0.146"/>
  <system-out/>
  <testcase classname="com.TestCases.LoginPageTestcases" name="txt3" time="0.121"/>
  <system-out/>
  <testcase classname="com.TestCases.LoginPageTestcases" name="ckhbox" time="0.180"/>
  <system-out/>
  <testcase classname="com.TestCases.LoginPageTestcases" name="login" time="5.365"/>
  <system-out/>
  <testcase classname="com.TestCases.LoginPageTestcases" name="ProfilenName" time="0.105"/>
  <system-out/>
  <testcase classname="com.TestCases.LoginPageTestcases" name="pagename" time="0.074"/>
  <system-out/>
  <testcase classname="com.TestCases.LoginPageTestcases" name="optionschk" time="9.913"/>
  <system-out/>
  <testcase classname="com.TestCases.LoginPageTestcases" name="Seacrhproduct" time="9.249"/>
  <system-out/>
  <testcase classname="com.TestCases.LoginPageTestcases" name="logout" time="2.843"/>
  <system-out/>
</testsuite> <!-- com.TestCases.LoginPageTestcases -->
